### ISSUE TITLE
Error: missing field `choices` at line 8 column 1

### ISSUE THREAD

**Issue by bhelx** [bradyjoslin/assembllm#19]
I saw you answered this in Discord but figured i'd document it here. When loading it up for the first time my openai response is invalid:

```
Error: missing field `choices` at line 8 column 1
```

After changing my API Key permissions i was able to get it to work:

```
Permissions: Restricted
Models: Read
Model capabilities: Write
Assistants: Read
Threads: Read
Fine tuning: None
Files: None
```

You might want to consider calling some kind of meta endpoint to check the API key. Or if the response is invalid add some extra detail to the error message about what may be the problem. Perhaps there is a header or status code you can go off of? Not very familiar with openai's API

**Comment by bradyjoslin** [comment]
This will likely need to be handled per plug-in, as may differ based on LLM service implementation.  Improving the error handling for the built-in plug-ins would definitely help onboarding.  

For now, noting a few options for troubleshooting.

A good way to check a tokens would be to call their service directly with curl.

OpenAI:

```sh
curl -v https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Who won the world series in 2020?"
      }
    ]
  }'
  ```
  
 Perplexity:
 
 ```sh
 curl --request POST \
     --url https://api.perplexity.ai/chat/completions \
     --header "Authorization: Bearer $PERPLEXITY_API_KEY" \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "model": "llama-3-sonar-small-32k-online",
  "messages": [
    {
      "role": "system",
      "content": "Be precise and concise."
    },
    {
      "role": "user",
      "content": "How many stars are there in our galaxy?"
    }
  ]
}
'
``` 

Cloudflare:

```sh
curl https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/ai/run/@cf/meta/llama-3-8b-instruct \
  -H "Authorization: Bearer $WORKERS_AI_TOKEN" \
  -d '{ "prompt": "Where did the phrase Hello World come from" }'
```

You can also test specific plug-ins directly via the [extism cli](https://github.com/extism/cli) with increased logging, like this:
  
  ```sh
  extism call https://cdn.modsurfer.dylibso.com/api/v1/module/114e1e892c43baefb4d50cc8b0e9f66df2b2e3177de9293ffdd83898c77e04c7.wasm completion \
        --set-config="{\"api_key\": \"$OPENAI_API_KEY\"}" \
        --input="Explain extism in the context of wasm succinctly." \
        --allow-host=api.openai.com --log-level=info
 ```

**Comment by bradyjoslin** [comment]
All plugins now have improved error handling to surface details from their respective API on non-200 responses. Updating to release 2.2+ will migrate the local configuration to use the latest plugins and keep them updated moving forward.
